# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Semantic Musing
email: charles.vardeman@gmail.com
description: >
  Musings about applying Linked Data, Semantics and Machine Learning to solve problems.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vardeman.me" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Charles F Vardeman II'
bio: >
  I'm a theoretical chemist in material science that wandered into the world of data.
  Currently a computational scientist using exploring Semantic Web, Linked Data and Machine Learning to solve problems.
author_image: "/assets/images/author.jpg"
twitter_username: charlesvardeman
github_username:  charlesvardeman

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
    #  - jekyll-json-ld
